development:
  adapter: postgresql
  database: tiredb_dev
  username: tiredb
  password: tiredb
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: tiresearch
  username: tiresearch
  password: gt-rbigwheel
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: tiredb
  username: tiredb
  password: tiredb
  host: localhost
  encoding: UTF8
